domain_path: C:\work\github\AXI_image\AXI_image_PS\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
